[workspace]
members = [
    "crates/phantom",
    "crates/phantom-net",
    "crates/phantom-profile",
    "crates/phantom-quic-btls",
    "crates/phantom-testkit",
]
exclude = ["vendor/btls", "vendor/http2"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.0"

[workspace.dependencies]
btls = { git = "https://github.com/0xARYA/btls", rev = "78b8c24a3388973d1d33c523995d311d766a1026", default-features = false }
btls-sys = { git = "https://github.com/0xARYA/btls", rev = "78b8c24a3388973d1d33c523995d311d766a1026", default-features = false }
tokio-btls = { git = "https://github.com/0xARYA/btls", rev = "78b8c24a3388973d1d33c523995d311d766a1026", default-features = false }
zeroize = "=1.9.0"

[patch.crates-io]
http2 = { path = "vendor/http2" }

[patch."https://github.com/0xARYA/btls"]
btls = { path = "vendor/btls" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
expect_used = "warn"
todo = "deny"
unimplemented = "deny"
unwrap_used = "warn"

[profile.bench]
debug = 1
