//! Encrypted Client Hello test material: fixed server keys, `ECHConfig`
//! encoding, and decoding of the outer `encrypted_client_hello` extension.

/// An X25519 HPKE key pair for a loopback ECH server.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct EchTestKey {
    /// The 32-byte X25519 private key, as `EVP_HPKE_KEY_init` takes it.
    pub private_key: [u8; 32],
    /// The matching 32-byte X25519 public key.
    pub public_key: [u8; 32],
}

/// Two fixed key pairs, so one server can publish a configuration the other
/// cannot decrypt.
///
/// They are the pairs in btls's `test/echkey`, `test/echconfig`,
/// `test/echkey-2`, and `test/echconfig-2`, generated by BoringSSL's
/// `bssl generate-ech`. They protect nothing.
pub const TEST_ECH_KEYS: [EchTestKey; 2] = [
    EchTestKey {
        private_key: [
            0x9f, 0x1d, 0xeb, 0x8c, 0xf5, 0x56, 0x35, 0xb3, 0x1f, 0x69, 0xab, 0x6e, 0x33, 0xef,
            0x00, 0x9e, 0x8a, 0xd7, 0x28, 0x19, 0x2d, 0xab, 0x12, 0x37, 0x94, 0x4b, 0xc7, 0x7c,
            0x3f, 0xa9, 0x1f, 0x82,
        ],
        public_key: [
            0xbb, 0x2f, 0x29, 0xe3, 0xe3, 0x05, 0x7e, 0x04, 0x19, 0xd5, 0x2f, 0xc5, 0xf4, 0x41,
            0x18, 0x77, 0x6f, 0x8d, 0xb6, 0x1c, 0xea, 0x4f, 0xdf, 0x76, 0x07, 0x9b, 0x93, 0x60,
            0x6c, 0x5a, 0x62, 0x48,
        ],
    },
    EchTestKey {
        private_key: [
            0xa7, 0x35, 0x44, 0x24, 0x6c, 0xfe, 0xb0, 0x53, 0x4c, 0x62, 0x7e, 0xca, 0x2e, 0x11,
            0x8f, 0x56, 0x3c, 0xc0, 0x2e, 0x6a, 0xa2, 0xe7, 0xaf, 0x3a, 0x7d, 0xb4, 0x72, 0x13,
            0x1e, 0x88, 0xb6, 0x85,
        ],
        public_key: [
            0x7e, 0xfb, 0x5f, 0xee, 0xa2, 0xa2, 0x74, 0xb3, 0xff, 0xfe, 0x69, 0x51, 0x9e, 0xfa,
            0xe1, 0xfa, 0x49, 0x8c, 0x61, 0x2c, 0xfa, 0xd0, 0x0f, 0x8c, 0x22, 0x87, 0x0e, 0xbc,
            0xb0, 0x2d, 0x76, 0x25,
        ],
    },
];

/// ECHConfig version of RFC 9849.
const VERSION: u16 = 0xfe0d;
/// `DHKEM(X25519, HKDF-SHA256)`.
const KEM_X25519_HKDF_SHA256: u16 = 0x0020;

/// Encodes one `ECHConfig` (RFC 9849 section 4) for `key`.
///
/// It offers HKDF-SHA256 with AES-128-GCM and with ChaCha20-Poly1305, as
/// `bssl generate-ech` does, a `maximum_name_length` of 0, and no
/// extensions.
///
/// # Panics
///
/// Panics when `public_name` is empty or longer than 255 bytes.
#[must_use]
pub fn ech_config(config_id: u8, key: &EchTestKey, public_name: &str) -> Vec<u8> {
    let name = public_name.as_bytes();
    assert!(
        !name.is_empty() && name.len() <= usize::from(u8::MAX),
        "public name must hold 1 to 255 bytes"
    );
    let mut contents = vec![config_id];
    contents.extend_from_slice(&KEM_X25519_HKDF_SHA256.to_be_bytes());
    contents.extend_from_slice(&32_u16.to_be_bytes());
    contents.extend_from_slice(&key.public_key);
    contents.extend_from_slice(&8_u16.to_be_bytes());
    contents.extend_from_slice(&[0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x03]);
    contents.push(0);
    contents.push(name.len() as u8);
    contents.extend_from_slice(name);
    contents.extend_from_slice(&0_u16.to_be_bytes());
    let mut config = VERSION.to_be_bytes().to_vec();
    config.extend_from_slice(&(contents.len() as u16).to_be_bytes());
    config.extend_from_slice(&contents);
    config
}

/// Encodes an `ECHConfigList` holding `configs` in order.
///
/// # Panics
///
/// Panics when the configurations exceed the list's 65535-byte limit.
#[must_use]
pub fn ech_config_list(configs: &[Vec<u8>]) -> Vec<u8> {
    let body = configs.concat();
    assert!(
        body.len() <= usize::from(u16::MAX),
        "ECHConfigList exceeds 65535 bytes"
    );
    let mut list = (body.len() as u16).to_be_bytes().to_vec();
    list.extend_from_slice(&body);
    list
}

/// The outer form of an `encrypted_client_hello` extension body
/// (RFC 9849 section 5): what a ClientHelloOuter carries, for real ECH and
/// for GREASE alike.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EchOuterExtension {
    /// HPKE KDF identifier of the chosen cipher suite.
    pub kdf_id: u16,
    /// HPKE AEAD identifier of the chosen cipher suite.
    pub aead_id: u16,
    /// `config_id` of the configuration used; random for GREASE.
    pub config_id: u8,
    /// Length of the HPKE encapsulated key.
    pub enc_length: usize,
    /// Length of the encrypted ClientHelloInner.
    pub payload_length: usize,
}

impl EchOuterExtension {
    /// Decodes an extension body of type `outer` (0).
    ///
    /// Returns `None` for another type or a malformed body.
    #[must_use]
    pub fn parse(body: &[u8]) -> Option<Self> {
        let (&kind, rest) = body.split_first()?;
        if kind != 0 {
            return None;
        }
        let (suite, rest) = rest.split_at_checked(4)?;
        let (&config_id, rest) = rest.split_first()?;
        let (enc_length, rest) = rest.split_at_checked(2)?;
        let enc_length = usize::from(u16::from_be_bytes([enc_length[0], enc_length[1]]));
        let (_, rest) = rest.split_at_checked(enc_length)?;
        let (payload_length, rest) = rest.split_at_checked(2)?;
        let payload_length =
            usize::from(u16::from_be_bytes([payload_length[0], payload_length[1]]));
        if rest.len() != payload_length {
            return None;
        }
        Some(Self {
            kdf_id: u16::from_be_bytes([suite[0], suite[1]]),
            aead_id: u16::from_be_bytes([suite[2], suite[3]]),
            config_id,
            enc_length,
            payload_length,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{EchOuterExtension, TEST_ECH_KEYS, ech_config, ech_config_list};

    #[test]
    fn encoded_config_matches_the_bssl_generated_one() {
        let expected = "fe0d003a0000200020bb2f29e3e3057e0419d52fc5f44118776f8db61cea4fdf76079b93\
                        606c5a62480008000100010001000300076563682e636f6d0000";
        let encoded = ech_config(0, &TEST_ECH_KEYS[0], "ech.com");
        let hex = encoded
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        assert_eq!(hex, expected);
        let list = ech_config_list(std::slice::from_ref(&encoded));
        assert_eq!(&list[..2], &(encoded.len() as u16).to_be_bytes());
    }

    #[test]
    fn outer_extension_decodes_its_fields() {
        let mut body = vec![
            0, 0x00, 0x01, 0x00, 0x03, 0x07, 0x00, 0x02, 0xaa, 0xbb, 0x00, 0x03,
        ];
        body.extend_from_slice(&[1, 2, 3]);
        assert_eq!(
            EchOuterExtension::parse(&body),
            Some(EchOuterExtension {
                kdf_id: 1,
                aead_id: 3,
                config_id: 7,
                enc_length: 2,
                payload_length: 3,
            })
        );
        body.push(4);
        assert_eq!(EchOuterExtension::parse(&body), None);
        assert_eq!(EchOuterExtension::parse(&[1]), None);
    }
}
